Repository Sergio0694/PolySharp, pull requests merged in 2023-01, with the labels that each got.

#33 Add workarounds to support .NET 3.5
  src/PolySharp.SourceGenerators/Models/GeneratedType.cs
  src/PolySharp.SourceGenerators/Models/SyntaxFixupType.cs
  src/PolySharp.SourceGenerators/PolyfillsGenerator.Execute.cs
  tests/PolySharp.NuGet/PolySharp.NuGet.csproj
Labels: enhancement

#34 Include readme in NuGet package
  README.md
  src/PolySharp.Package/PolySharp.Package.msbuildproj
Labels: enhancement

#35 Switch UnsupportedCSharpLanguageVersionAnalyzer to analyzer
  src/PolySharp.SourceGenerators/Diagnostics/Analyzers/UnsupportedCSharpLanguageVersionAnalyzer.Execute.cs
  src/PolySharp.SourceGenerators/Diagnostics/Analyzers/UnsupportedCSharpLanguageVersionAnalyzer.cs
Labels: enhancement

#36 Fix README.md being packed twice
  src/PolySharp.Package/PolySharp.Package.msbuildproj
Labels: bug

#37 Fix formatting of packed README file
  src/PolySharp.Package/PolySharp.Package.msbuildproj
  src/PolySharp.Package/README.md
Labels: enhancement

#27 Specify the minimum .NET 6 SDK
  src/PolySharp.SourceGenerators/PolySharp.targets
Labels: documentation

#38 Refactor pipeline to not flow Compilation objects
  src/PolySharp.SourceGenerators/Models/AvailableType.cs
  src/PolySharp.SourceGenerators/PolyfillsGenerator.Execute.cs
  src/PolySharp.SourceGenerators/PolyfillsGenerator.cs
Labels: enhancement

#40 Add PolySharpUseTypeAliasForUnmanagedCallersOnlyAttribute MSBuild option
  PolySharp.sln
  README.md
  src/PolySharp.SourceGenerators/Constants/PolySharpMSBuildProperties.cs
  src/PolySharp.SourceGenerators/Models/GenerationOptions.cs
  src/PolySharp.SourceGenerators/Models/SyntaxFixupType.cs
  src/PolySharp.SourceGenerators/PolySharp.targets
  src/PolySharp.SourceGenerators/PolyfillsGenerator.Execute.cs
  tests/PolySharp.PolySharpUseTypeAliasForUnmanagedCallersOnlyAttribute.Tests/PolySharp.PolySharpUseTypeAliasForUnmanagedCallersOnlyAttribute.Tests.csproj
  tests/PolySharp.PolySharpUseTypeAliasForUnmanagedCallersOnlyAttribute.Tests/UnmanagedCallersOnlyAttributeTests.cs
Labels: enhancement

#42 Generate [TypeForwardsTo] when needed
  .github/workflows/dotnet.yml
  PolySharp.sln
  README.md
  src/PolySharp.Package/README.md
  src/PolySharp.SourceGenerators/Constants/PolySharpMSBuildProperties.cs
  src/PolySharp.SourceGenerators/Diagnostics/Analyzers/InvalidPolySharpMSBuildOptionAnalyzer.Execute.cs
  src/PolySharp.SourceGenerators/Extensions/CompilationExtensions.cs
  src/PolySharp.SourceGenerators/Models/GenerationOptions.cs
  src/PolySharp.SourceGenerators/Models/SyntaxFixupType.cs
  src/PolySharp.SourceGenerators/PolySharp.targets
  src/PolySharp.SourceGenerators/PolyfillsGenerator.Polyfills.cs
  src/PolySharp.SourceGenerators/PolyfillsGenerator.TypeForwards.cs
  src/PolySharp.SourceGenerators/PolyfillsGenerator.cs
  tests/PolySharp.PolySharpUseTypeAliasForUnmanagedCallersOnlyAttribute.Tests/PolySharp.PolySharpUseTypeAliasForUnmanagedCallersOnlyAttribute.Tests.csproj
  tests/PolySharp.Tests/LanguageFeatures.cs
  tests/PolySharp.Tests/PolySharp.Tests.csproj
  tests/PolySharp.TypeForwards.Tests/PolySharp.TypeForwards.Tests.csproj
  tests/PolySharp.TypeForwards.Tests/TypeForwardTests.cs
Labels: enhancement

#52 Add [RequiresDynamicCode] polyfill
  README.md
  src/PolySharp.Package/README.md
  src/PolySharp.SourceGenerators/EmbeddedResources/RuntimeSupported/System.Diagnostics.CodeAnalysis.RequiresDynamicCodeAttribute.cs
  tests/PolySharp.Tests/RuntimeSupport.cs
Labels: enhancement

#54 Add [DisableRuntimeMarshalling] polyfill
  README.md
  src/PolySharp.Package/README.md
  src/PolySharp.SourceGenerators/EmbeddedResources/RuntimeSupported/System.Runtime.CompilerServices.DisableRuntimeMarshallingAttribute.cs
  tests/PolySharp.Tests/RuntimeSupport.cs
Labels: enhancement

#55 Add missing MULTI_TARGETING_SUPPORT_ATTRIBUTES attributes
  src/PolySharp.SourceGenerators/EmbeddedResources/RuntimeSupported/System.Diagnostics.CodeAnalysis.RequiresDynamicCodeAttribute.cs
  src/PolySharp.SourceGenerators/EmbeddedResources/RuntimeSupported/System.Runtime.CompilerServices.DisableRuntimeMarshallingAttribute.cs
Labels: bug
